// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1_UkECLu4WdAKnYkYC2NjM4zOAJ5Nc3Y',
    appId: '1:570778418983:web:f5485a87684f008fd03302',
    messagingSenderId: '570778418983',
    projectId: 'brew-crew-b4b36',
    authDomain: 'brew-crew-b4b36.firebaseapp.com',
    storageBucket: 'brew-crew-b4b36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWLcgWjRr2e2AVj-PdahHBVq6fGmaEuqU',
    appId: '1:570778418983:android:e6a5a1805aa63e39d03302',
    messagingSenderId: '570778418983',
    projectId: 'brew-crew-b4b36',
    storageBucket: 'brew-crew-b4b36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEPXg5lIUHCHCSjUhb26PI6yoK82LfNAs',
    appId: '1:570778418983:ios:0ee016daba2a6ad1d03302',
    messagingSenderId: '570778418983',
    projectId: 'brew-crew-b4b36',
    storageBucket: 'brew-crew-b4b36.appspot.com',
    iosClientId: '570778418983-sjtkd8j8d6qv3o7tekm3roekt6qb3dg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEPXg5lIUHCHCSjUhb26PI6yoK82LfNAs',
    appId: '1:570778418983:ios:5f9cb4f114be653bd03302',
    messagingSenderId: '570778418983',
    projectId: 'brew-crew-b4b36',
    storageBucket: 'brew-crew-b4b36.appspot.com',
    iosClientId: '570778418983-b2t3k4kocc2ddtk0iadon80abeghi9ek.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew.RunnerTests',
  );
}
